iters: 16000 # 400*40
checkpoint_dir: ${paths.log_dir}/${experiment}/checkpoints
save_iter: 400
budget: 0.3
clipping: 2

tensorboard_path: ${paths.log_dir}/${experiment}/tensorboard

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.00001
  weight_decay: 0.0001
