name: ASPS

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  - pytorch==2.1.*
  - torchvision

  - opencv==4.9.*

  - hydra-core
  - tqdm

  - pip>23
  - pip:
    - onnx
    - onnxruntime
    - pre-commit
    - rootutils
    - albumentations==1.3.0
    - mmcv-full==1.6.2
