vit_settings:
  selected: "vit_h"
  huge:
    model_type: "vit_h"
    encoder_embedding_dimension: 1280
    encoder_depth: 32
    encoder_number_of_attention_heads: 16
    encoder_global_attention_indexes: [7, 15, 23, 31]
    checkpoint: "pretrained/sam_vit_h_4b8939.pth"
  large:
    model_type: "vit_l"
    encoder_embedding_dimension: 1024
    encoder_depth: 24
    encoder_number_of_attention_heads: 16
    encoder_global_attention_indexes: [5, 11, 17, 23]
    checkpoint: None
  base:
    model_type: "vit_b"
    encoder_embedding_dimension: 768
    encoder_depth: 12
    encoder_number_of_attention_heads: 12
    encoder_global_attention_indexes: [3, 6, 9, 12]
    checkpoint: "pretrained/sam_vit_b_01ec64.pth"
